module.exports = {
  charset: "utf-8",
  assetsCharset: "utf-8",
  css: ".css",
  js: ".js",
  cdnPath: '/',
  version: '',
  sourcemap: false,
  random: false,
  replaces: {},
  remote: {},
  hosts: {},
  filter: {},
  ignoreTokens: [],
  ignoreJuicer: [],
  ignorePretty: [],
  native2ascii: false,
  cache: true,
  strictPage: false
};