module.exports = {
  charset: "utf-8",
  assetsCharset: "utf-8",
  css: ".css",
  js: ".js",
  cdnPath: '',
  version: '',
  layout: "default.vm",
  screenPlaceholder: "screen_placeholder",
  sourcemap: false,
  random: false,
  replaces: {},
  remote: {},
  hosts: {},
  filter: {},
  supportedFile: [],
  ignoreTokens: [],
  ignoreJuicer: [],
  native2ascii: false,
  cache: true,
  strictPage: false
};